### PR TITLE
Migrations are now applied by collection

### PR DESCRIPTION
**Pull request by MathieuMathurin**
I propose to track migrations by collection instead of by database.

### CODE REVIEW

**Comment by VladimirRybalko** [comment]
Hi @MathieuMathurin 
I'm a just curious.  What's the purpose? 
Do you want to apply migrations for each collections separately?
For example: run migrations for collection **A** only, and don't touch collection **B** even if you have some migrations for **B**. Am I right?

**Comment by MathieuMathurin** [comment]
Hi @VladimirRybalko 

I'm trying to get the same behavior as FluentMigrator which applies migration to a specific schema. The migration will be easier to maintain if we can link them to a collection. That way we won't have to keep track of a global version number, but instead to track a specific one by collection.

Clearly my solution brings some breaking changes, it might be nice to try to figure out how to override the behavior instead of just replacing it.

**Comment by VladimirRybalko** [comment]
Hi @MathieuMathurin 
It's a very interesting idea. I'm going to figure out how we can implement it in a safety way without breaking changes.

**Comment by VladimirRybalko** [comment]
@MathieuMathurin 
Thank you very much for the good idea.
I've finally implemented the collection specific migrations into the master branch. So, now, you can use a package to cover your requirements.

**Pull request closed without merging**
